PLTS-15: 회원 탈퇴 후 재가입시 이메일 중복 에러 해결
PlanIt-Study/Planit-Server pull request #79
Opened 2022-01-18 06:33 UTC by audgnssweet

# PLTS-15: 회원 탈퇴 후 재가입시 이메일 중복 에러 해결

## 변경점
1. 회원 탈퇴 후 재가입시 deletedAt만 다시 null로 변경해주도록 수정
2. 추천인 등록 관련 로직의 책임 분리

## API 변경 사항
X

## SQL
X

## 기타 유의사항
X

2022-01-18 06:35 UTC, audgnssweet commented on src/main/kotlin/com/planit/recommendation/service/RecommendationCommandHandler.kt
> +}
회원가입시 추천인 등록 로직의 책임을 service로 분리했습니다.
단일 책임을 설정하기에 좋다고 판단했습니다.

2022-01-18 06:47 UTC, audgnssweet commented on src/main/kotlin/com/planit/user/service/impl/UserCommandHandlerImpl.kt
>          }
재가입시에도 같은 API를 호출하여 같은 DTO를 받는데, 만약 예전 회원 정보와 변경 사항이 있다면 어떻게 해야할지 모르겠습니다

현재는 deletedAt만 null로 바꿔주는데, 다른 필드들도 변경을 해줘야겠죠?

2022-01-18 13:22 UTC, sang-w0o commented on src/main/kotlin/com/planit/recommendation/service/impl/RecommendationCommandHandlerImpl.kt
> +    @Transactional
이 메소드는 꼭 `UserCommandHandler` 구현체에서 호출되니 
`@Transactional(propagation = MANDATORY)` 로 하는거 어떨까요?

2022-01-18 13:25 UTC, sang-w0o commented on src/main/kotlin/com/planit/user/domain/User.kt
> +    }
다른 `User`와 닉네임을 비교하는 거라면 메소드화할만 할 것 같은데, 단지 `String` 인자를 받아서 비교하는 부분을 메소드화한 이유가 궁금해요!

2022-01-18 16:23 UTC, audgnssweet reviewed
음 우선 나머지를 다 지워야 한다면 새로운 task로 빼는게 좋을 것 같아요

그런데 재가입시 리워드가 초기화되는건 정책상 그럴 수 있다고 생각하는데
예전에 했던 공부 내역들이 전부 사라져야 하는건 어떤 이유에서인가요??

제가 사용자라면 오히려 남아있는게 좋을 것 같아서 이 부분이 궁금해요.
쓰다가 탈퇴 하고 다시 사용하려고 들어왔는데 예전 내역들이 없으면 미련없이 다른 어플로 갈아탈 수 있지 않을까요??
공부 관련 자료로 통계를 낸다고 해도, 탈퇴 전 내역이 포함된다 해서 크게 문제될게 없다고 생각도 들어요

답변 기다리겠습니다~!~!~!~!~!

2022-01-18 16:23 UTC, audgnssweet commented on src/main/kotlin/com/planit/user/domain/User.kt
> +    }
객체지향에서 `getter를 사용하지 말고 객체에 메시지를 보내라` 라는 원칙이 있어서 한번 적용해보았습니다.
getter를 사용하면 사용의 의도가 명확하지 않고 자칫 잘못하면 올바르지 않은 값이 대입될 수 있다고 해가지구요

사실 메서드 자체가 별거 아니라 안 그래도 상관은 없지만 유저 객체에게 메시지를 보낸다는 측면에서 보면 객체지향적이기도 하고,
혹은 해당 service 말고 다른 곳에서도 도메인만으로 재활용 할 수 있는 여지가 있다거나,
다른 user 객체와 비교할 때도
```kotlin
fun isNicknameExactly(nickname: String): Boolean {
    return this.nickname == nickname
}

fun hasSameNicknameWith(other: User) {
    return isNicknameExactly(other.nickname)
}
```
처럼 재사용될 수도 있다고 생각합니다.

하지만 그닥 중요한건 아니라 메서드로 이렇게 분리하지 않아도 전혀 문제 없다고 생각합니다~!

2022-01-18 16:23 UTC, audgnssweet commented on src/main/kotlin/com/planit/user/service/impl/UserCommandHandlerImpl.kt
>          }
혹시 이부분에 대해서는 어떻게 생각하시나요??

2022-01-18 16:23 UTC, audgnssweet commented on src/test/kotlin/com/planit/integration/user/UserSignupTest.kt
> +        )
하하.... 상우님이 주신 책 이제 5페이지 봤습니다...

2022-01-18 16:31 UTC, audgnssweet commented on src/main/kotlin/com/planit/user/service/impl/UserCommandHandlerImpl.kt
>          }
> 재가입시에도 같은 API를 호출하여 같은 DTO를 받는데, 만약 예전 회원 정보와 변경 사항이 있다면 어떻게 해야할지 모르겠습니다
> 
> 현재는 deletedAt만 null로 바꿔주는데, 다른 필드들도 변경을 해줘야겠죠?

혹시 이 부분에 대해서는 어떻게 생각하시나요??

2022-01-19 02:22 UTC, sang-w0o commented on src/main/kotlin/com/planit/user/service/impl/UserCommandHandlerImpl.kt
>          }
네 다른 필드들도 변경해야 할 것 같아요!

2022-01-19 02:29 UTC, sang-w0o commented on src/main/kotlin/com/planit/user/domain/User.kt
> +    }
음 일단 너무 객체지향적 이라는 단어에 얽매이지 않아도 될 것 같아요.

후니님이 *User 객체에게 메시지를 보낸다*고 하셨는데, 그럼 User 객체에서 상태를 바꾸거나 다른 객체의 메소드를 호출하는게 맞다고 보는데, 이건 단순히 문자열 비교잖아요! nickname이 만약 private property 였다면 어쩔 수 없이 메소드화할 수 밖에 없구요.

위에서 들어주신 코드 예시는 재활용이 아니라, 시그니처가 아예 다르기에 서로 다른 메소드 2개 아닌가요?

2022-01-19 02:45 UTC, audgnssweet commented on src/main/kotlin/com/planit/user/domain/User.kt
> +    }
네 말씀해주신 부분도 맞다고 생각합니다.
하지만 단순 문자열 비교일지라도 해당 닉네임은 해당 유저만의 고유한 정보니까요...!
상태를 바꾸거나 다른 객체의 메서드를 호출하지 않더라도 '메시지를 보낸다' 
-> 객체 고유의 정보로 스스로 판단한다 는 부분에서 아예 틀린 것은 아니라고 생각합니다.

너무 오버엔지니어링이라고 생각하시면 다시 코멘트 남겨주세요 수정하겠습니다

2022-01-19 06:23 UTC, sang-w0o commented on src/main/kotlin/com/planit/user/domain/User.kt
> +    }
네 솔직히 저는 오버엔지니어링이라 생각들어요.
나중에 코드를 짤 때 특정 user의 nickname과 String nickname을 비교해야 할때,
자연스럽게 그 비교를 수행해주는 메소드가 `User`에 있다고 생각들지 않을 것 같아서요..

근데 이건 답이 없는 논제라서, 저도 꼭 제 생각을 강요하고 싶지는 않아요! 
다만, 위에 쓴 생각은 진짜입니다ㅜㅜ

2022-01-19 12:44 UTC, audgnssweet reviewed
추가로 코멘트 남겼습니다~!

2022-01-19 12:47 UTC, audgnssweet commented on src/main/kotlin/com/planit/recommendation/service/impl/RecommendationCommandHandlerImpl.kt
> +    override fun provideRecommendationCompensation(user: User, receiverNickname: String) {
이것도 provideRecommendationReward 로 바꿔볼 생각이에요

2022-01-20 04:49 UTC, sang-w0o requested changes

2022-01-20 04:49 UTC, sang-w0o commented on src/main/kotlin/com/planit/user/domain/User.kt
> +    }
네 아마 변경 가능한 필드들은 모두 var로 두는게 나을 것 같아요.
다만, 아직 기획이 확정난게 아니니 지금은 val로 가고, 이후에 수정이 가능하다 할 때
해당 task에서 var로 수정하는게 좋을 것 같아요!

2022-01-20 04:49 UTC, sang-w0o commented on src/main/kotlin/com/planit/user/service/impl/UserCommandHandlerImpl.kt
> +                validateNicknameNotDuplicated(nickname)
생각해보니까 탈퇴한 회원이 a라는 nickname을 사용했다면 `validateNicknameNotDuplicated()`에서 호출하는 레포지토리 메소드에서 날리는 쿼리에 `WHERE deleted_at IS NULL` 조건이 붙으니까 false가 될 것이고, 로직을 통과하게 되니까 save 시에 에러가 나겠네요! (nickname은 table 단에 unique constraint가 있어요)

`validateNicknameNotDuplicated()`에서 호출하는 레포지토리 메소드를 `existsByNickname()` 으로 해야할 것 같아요!
이거 때문에만 request changes 해놓을게요!!

2022-01-20 05:18 UTC, audgnssweet commented on src/main/kotlin/com/planit/user/service/impl/UserCommandHandlerImpl.kt
> +                validateNicknameNotDuplicated(nickname)
수정했습니다~!

2022-01-20 05:23 UTC, audgnssweet commented on src/main/kotlin/com/planit/user/domain/UserRepository.kt
> -    fun existsByEmailAndDeletedAtIsNull(email: String): Boolean
어 이거 왜없어졌죠..? 확인해볼게요

2022-01-21 01:20 UTC, sang-w0o approved these changes
굳!! 고생하셨습니다 :)

2022-01-21 04:25 UTC, merged